/** A single row from the ping_responses table. */
export interface PingRecord {
  /** Primary key (UUID v4) */
  id: string;
  /** Start of the 5-minute UTC bucket — UNIQUE constraint prevents duplicate ticks */
  intervalKey: Date;
  /** Server-side insert timestamp */
  createdAt: Date;
  /** Random JSON payload sent to httpbin */
  requestPayload: Record<string, unknown>;
  /** HTTP status code; null when no response was received */
  responseStatus: number | null;
  /** Parsed response body from httpbin */
  responseBody: Record<string, unknown> | null;
  /** True if body was truncated before storage */
  responseBodyTruncated: boolean;
  /** Round-trip latency in ms; null on total failure */
  latencyMs: number | null;
  /** False on network/timeout/unrecoverable error */
  success: boolean;
  /** Short error detail when success is false */
  errorMessage: string | null;
}

/**
 * Inserts a ping result into the database.
 *
 * TODO: Implement INSERT with interval_key UNIQUE handling.
 * - Use ON CONFLICT or catch unique violation
 * - Map camelCase input to snake_case columns
 *
 * @param record - Ping data to persist (id and createdAt are generated by DB)
 * @returns The inserted row with DB-generated fields
 */
export async function insertPing(
  _record: Omit<PingRecord, "id" | "createdAt">
): Promise<PingRecord> {
  throw new Error("Not implemented");
}

/**
 * Fetches historical ping responses, newest first.
 *
 * TODO: Implement SELECT with pagination.
 * - ORDER BY created_at DESC
 * - Map snake_case columns to camelCase PingRecord
 *
 * @param options - Pagination controls
 * @returns Array of ping records
 */
export async function getPings(_options: {
  limit?: number;
  offset?: number;
}): Promise<PingRecord[]> {
  throw new Error("Not implemented");
}
